select 	top 100
        d.den_cd as denuncia,
        d.den_logr_tp, 
        d.den_logr_ds, 
        d.den_logr_num, 
        d.den_logr_bairro, 
        d.den_logr_subbairro, 
        d.den_logr_cep, 
        d.den_logr_mun , 
        d.den_loc_ref,
        d.den_dt_rec,
        at.tpa_cd as assunto_cd,
        at.tpa_ds as assunto,
        at.tpa_cla_cd as fk_assunto_classe,
        at.tpa_st as assunto_status,
        cla.cla_cd,
        cla.cla_ds,
        cla.cla_st,
        x2.xpt_cd as xpto_cd,
        x2.xpt_ds as xpto,
        x2.xpt_st as xpto_status,
        m.mul_cd as mulher_cd,
        m.mul_den_cd,
        m.mul_lugar,
        m.mul_vive,
        m.mul_filhos,
        m.mul_filhos_qtd,
        m.mul_filhos_agd,
        m.mul_agr_alcool,
        m.mul_quando,
        m.mul_freq,
        m.mul_hora,
        m.mul_test,
        m.mul_t_pai_vit,
        m.mul_t_mae_vit,
        m.mul_t_pai_agr,
        m.mul_t_mae_agr,
        m.mul_t_filhos,
        m.mul_t_outros,
        m.mul_t_ods,
        m.mul_data,
        m.mul_tpag_fisica,
        m.mul_tpag_verbal,
        m.mul_tpag_sexual,
        m.mul_tpag_carcere,
        m.mul_tpag_ameaca,
        m.mul_tpag_ninform,
        m.mul_tpag_outros,
        m.mul_tpag_ods,
        m.mul_agr_ab,
        m.mul_agr_af,
        m.mul_agr_pau,
        m.mul_agr_fio,
        m.mul_agr_cig,
        m.mul_agr_mao,
        m.mul_agr_est,
        m.mul_agr_soc,
        m.mul_agr_emp,
        m.mul_agr_chu,
        m.mul_agr_out,
        m.mul_agr_ods,
        v.vei_cd as veiculos_cd,
        vei_marca.mar_ds,
        vm.mod_ds,
        v.cor,
        v.ano_mod,
        v.ano_fab,
        v.placa,
        v.municipio,
        v.uf,
        v.chassis,
        v.proprietario,
        v.com_nome,
        v.com_endereco,
        v.com_bairro,
        v.com_municipio,
        v.com_uf,
        v.com_telefone,
        v.com_doc,
        v.com_tipo,
        v.ro_dp,
        v.seguradora,
        v.detalhes
        
        
from 
		((dd.dbo.assunto_denuncia a full  JOIN dd.dbo.assunto_tipo at ON (a.ass_tpa_cd = at.tpa_cd) full JOIN dd.dbo.assunto_classe cla ON (cla.cla_cd=at.tpa_cla_cd)) full  JOIN dd.dbo.denuncia d ON (d.den_cd = a.ass_den_cd))    
		full outer join 
		((dd.dbo.xpto x2  join dd.dbo.xpto_denuncia x3 on (x2.xpt_cd=x3.dxp_xpt_cd)) join dd.dbo.denuncia d2 on (x3.dxp_den_cd=d2.den_cd))
		 on (d2.den_cd = d.den_cd)
          full join (dd.dbo.dd_mulher m  join dd.dbo.denuncia d3 on (m.mul_den_cd=d3.den_cd)) on (d3.den_cd=d.den_cd)
		 full join (dd.dbo.veiculos v join dd.dbo.vei_modelo vm on(v.marca=vm.mod_cd) join dd.dbo.vei_marca vei_marca ON (vei_marca.mar_cd=vm.mar_cd) join dd.dbo.denuncia d4 on (v.den_cd=d4.den_cd)) on (d4.den_cd=d.den_cd)
   where d.den_cd is not NULL
	order by d.den_cd